Repository apache/maven-mvnd, pull requests merged in 2024-07, with the labels that each got.

#1055 [1.x] Separate message and exception by newline
  logging/src/main/java/org/slf4j/impl/MvndSimpleLogger.java
Labels: backport

#1056 [1.x] Fix user properties interpolation and maven.multiModuleProjectDirectory (fixes #1031)
  client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
  daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
  integration-tests/src/test/java/org/mvndaemon/mvnd/it/MavenConfNativeIT.java
  integration-tests/src/test/java/org/mvndaemon/mvnd/it/MavenConfTest.java
Labels: backport

#1057 Fix maven.multiModuleProjectDirectory (fixes #1031)
  client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
  integration-tests/src/test/java/org/mvndaemon/mvnd/it/MavenConfIgnoreExtNativeIT.java
  integration-tests/src/test/java/org/mvndaemon/mvnd/it/MavenConfNativeIT.java
Labels: bug

#1071 Fix daemon connection issues
  daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
Labels: bug, backport
